#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#

sh /etc/init.d-posix/10016_iris

if [ $AUTOCNF = yes ]
then
	# enable fusion of landing target velocity
	param set LTEST_MODE 0
	param set PLD_HACC_RAD 0
fi

# Startup obstacle avoidance
#obstacle_avoidance
